# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenapps

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickenapps.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1fe892ccd71e4f00b2257a5a8b916081 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_19ee7a09c5f4436da4cfd1ba751d9cf1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickenapps.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1fe892ccd71e4f00b2257a5a8b916081 }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenapps'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f6d1bed4f4aa4fac9f31e04702b5ce20 }}
        images: 'chickenapps.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1fe892ccd71e4f00b2257a5a8b916081 }}/chicken:${{ github.sha }}'